app_config:
  package_name: "sql_injection"
  training_data_file: "sql_injection_dataset.csv"

ml_model_config:
  features:
    - Query  # âœ… Use a proper YAML list
  target: Label
  test_size: 0.2
  random_state: 42
  n_estimators: 100
  max_depth: 10

